name: tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    name: tests
    env:
      # prevents extra Cypress installation progress messages
      CI: 1
    steps:
      - uses: actions/checkout@v1
      # install NPM dependencies but SKIP Cypress binary installation
      # see https://on.cypress.io/installing-cypress#Environment-variables
      - uses: bahmutov/npm-install@v1
        env:
          CYPRESS_INSTALL_BINARY: 0
      # confirm there is no Cypress installed
      - run: npx cypress cache path
      # should return empty list of installed versions
      - run: npx cypress cache list
      # restore / cache the binary ourselves on Linux
      # see https://github.com/actions/cache
      - name: Cache Cypress
        id: cache-cypress
        uses: actions/cache@v1
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package.json') }}
      # now let's install Cypress binary
      - run: npx cypress install
      - run: npx cypress cache list
      # and run Cypress tests
      - run: npx cypress run
      # Cypress binary will be cached after successful workflow finish
